### ISSUE TITLE
Search Bar in docs page

### ISSUE THREAD

**Issue by abdfnx** [secman-team/secman.dev#44]
we need to add search bar in https://secman.vercel.app/docs

now

**Comment by Timothee-Cardoso** [comment]
Ok, but what we well use ?

**Comment by abdfnx** [comment]
I think algolia is nice, What do you think ?

**Comment by Timothee-Cardoso** [comment]
Ok, it's not bad

**Comment by abdfnx** [comment]
Let's Start

**Comment by abdfnx** [comment]
Listen @Timothee-Cardoso , with algolia there's many errors, I try everything but no result

so what we well do ?

**Comment by Timothee-Cardoso** [comment]
What do you think about **meilisearch**, it's easy

**Comment by Timothee-Cardoso** [comment]
look at **https://docs.meilisearch.com**

**Comment by abdfnx** [comment]
Ok I'll try it

**Comment by Timothee-Cardoso** [comment]
I try to add meilisearch to our website, but there's many errors are come with it, so we should leave meilisearch.

**Comment by abdfnx** [comment]
> @abdfnx, I try to add meilisearch to our website, but there's many errors are come with it, so we should leave meilisearch.

oh no, this is not good news 😐.

**Comment by abdfnx** [comment]
so we must find another search engine 🔍

**Comment by Timothee-Cardoso** [comment]
I'll search, if I find a good one, I going to tell you, OK

**Comment by abdfnx** [comment]
ok

**Comment by abdfnx** [comment]
ok let's try **algolia** one more time

**Comment by abdfnx** [comment]
we did it, search bar engine was fixed... finally

**Comment by Timothee-Cardoso** [comment]
finally, what search engine do you use ?

**Comment by abdfnx** [comment]
algolia, I fix all errors
