### ISSUE TITLE
Big Idea

### ISSUE THREAD

**Issue by Timothee-Cardoso** [secman-team/secman.dev#45]
@abdfnx @iMRxM7mD , I see the **home** page is boring, also the website not very Professional site.

so I think we move to [`Docusaurus`](https://docusaurus.io).

this platform has many featuers.

1. Supports Markdown.
2. Also You can use React.
3. Has Algolia Search (You Just Need API Key And Index Name).
4. And it's very easy.

**Comment by abdfnx** [comment]
You mean **docusaurus** from **FOS** (Facebook Open Source) ?

**Comment by Timothee-Cardoso** [comment]
Yes it is

let's try it

**Comment by abdfnx** [comment]
sure, but I well create a release to save this website if docusaurus was failed

**Comment by abdfnx** [comment]
done
