### ISSUE TITLE
bugs in styling

### ISSUE THREAD

**Issue by Timothee-Cardoso** [secman-team/secman.dev#51]
there're three bugs

1. favicon
![2021-05-17 (1)](https://user-images.githubusercontent.com/80710181/118485103-a6c99f80-b720-11eb-8627-0365a5652a85.png)

2. algolia search buttons
![2021-05-17 (2)](https://user-images.githubusercontent.com/80710181/118485215-d11b5d00-b720-11eb-8161-ca83d6837d91.png)
> it's should be like this
![2021-05-17 (3)](https://user-images.githubusercontent.com/80710181/118485341-fad48400-b720-11eb-96ef-9544eeae2dda.png)

3. footer

![2021-05-17 (4)](https://user-images.githubusercontent.com/80710181/118485620-543cb300-b721-11eb-8290-bedfa03df494.png)

these bugs must be fixed

**Comment by abdfnx** [comment]
It's weird, in `dev` mood, the website is very nice, but in `production` mood, it's has weird things

> look at this 👇

![2021-05-17 (5)](https://user-images.githubusercontent.com/64256993/118486143-efce2380-b721-11eb-8903-67466bfeb5b2.png)

![2021-05-17 (5)2](https://user-images.githubusercontent.com/64256993/118486149-f2307d80-b721-11eb-91e4-59a53533df38.png)

![2021-05-17 (6)](https://user-images.githubusercontent.com/64256993/118486158-f492d780-b721-11eb-8d97-5a0d0ede1607.png)

everything is good in `dev` mood

**Comment by abdfnx** [comment]
but also the **favicon** doesn't show in `dev` mood 🤨

**Comment by abdfnx** [comment]
fixed

**Comment by Timothee-Cardoso** [comment]
👌👍
